package zad1;
//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class LoginWindow extends JDialog {
  private JTextField jcomp1;
  private JLabel jcomp2;
  private JButton jcomp3;

  public LoginWindow(ChatWindow cw) {
  //public LoginWindow(Client client) {
	  super(cw, "Enter nick", true);
	  
      //construct components
      jcomp1 = new JTextField (5);
      jcomp2 = new JLabel ("Enter nick and click OK");
      jcomp3 = new JButton ("OK");

      //adjust size and set layout
      setPreferredSize (new Dimension (229, 117));
      setLayout (null);

      //add components
      add (jcomp1);
      add (jcomp2);
      add (jcomp3);

      //set component bounds (only needed by Absolute Positioning)
      jcomp1.setBounds (10, 45, 210, 25);
      jcomp2.setBounds (10, 10, 210, 25);
      jcomp3.setBounds (10, 80, 210, 25);
      
      jcomp3.addActionListener(e->{
    	  cw.setNick(jcomp1.getText());
    	  dispose();
      });
      
      setDefaultCloseOperation (JFrame.DO_NOTHING_ON_CLOSE);
      //pack();
      setLocationRelativeTo(cw);
      setSize(235,150);
      setResizable(false);
      setVisible (true);
  }
  
}
